### ISSUE TITLE
Value Error - list namespaced config map 

### ISSUE THREAD

**Issue by johscheuer** [kubernetes-incubator/client-python#104]
Hi,

I have he following code snippet (I want all config maps in a specific namespace):

```python
api_instance = client.CoreV1Api()
api_response = None
try:
    api_response = api_instance.list_namespaced_config_map(namespace, pretty=True)
except ApiException as e:
    print("Exception when calling CoreV1Api->list_namespaced_config_map: %s\n" % e)
```

but when I execute it I get the following Error (if no config map exists in the namespace) :

```bash
python3 quobyte-k8s-deployer.py                                                                                                                                                                        
Traceback (most recent call last):
  File "quobyte-k8s-deployer.py", line 126, in <module>
    main()
  File "quobyte-k8s-deployer.py", line 112, in main
    create_configmap(quobyte_config['namespace'], quobyte_config['kubernetes_files']['path'])
  File "quobyte-k8s-deployer.py", line 45, in create_configmap
    api_response = api_instance.list_namespaced_config_map(namespace, pretty=True)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12359, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12463, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 328, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 281, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 629, in __deserialize_model
    setattr(instance, attr, self.__deserialize(value, attr_type))
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1_config_map_list.py", line 108, in items
    raise ValueError("Invalid value for `items`, must not be `None`")
ValueError: Invalid value for `items`, must not be `None`
```

So I added the following part as workaround:

```python
except ValueError:
    # no config maps found
    pass
```

I wanted to ask if this behaviour is wanted, actually I thought the items list would be empty like this if there are no existing config maps:

```json
{"api_version": "v1",
 "items": null,
 "kind": "ConfigMapList",
 "metadata": {"resource_version": "3049",
              "self_link": "/api/v1/namespaces/quobyte/configmaps"}}
```

How to reproduce:

execute `api_instance.list_namespaced_config_map(namespace, pretty=True)` on an namespace without config maps.

Thanks!

**Comment by johscheuer** [comment]
Seems to appear on all namespaced list actions e.q. `list_namespaced_service` and if you are using `field_selector`
