### ISSUE TITLE
upgrade failure in virtualenv 

### ISSUE THREAD

**Issue by mrmcmuffinz** [kubernetes-incubator/client-python#141]
**Scenario**
Trying to upgrade from fresh installed `v1.0.0.b1` to `v1.0.0b3` on my mac and I get an error

**Output**
```
(kpclient) Abrahams-MBP:qa acabrer$ python -m pip install kubernetes --upgrade
Collecting kubernetes
  Downloading kubernetes-1.0.0b3-py2.py3-none-any.whl (577kB)
    100% |████████████████████████████████| 583kB 1.1MB/s 
Requirement already up-to-date: pyyaml in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/PyYAML-3.12-py2.7-macosx-10.12-x86_64.egg (from kubernetes)
Requirement already up-to-date: python-dateutil in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/python_dateutil-2.6.0-py2.7.egg (from kubernetes)
Requirement already up-to-date: urllib3 in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/urllib3-1.20-py2.7.egg (from kubernetes)
Requirement already up-to-date: certifi in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/certifi-2017.1.23-py2.7.egg (from kubernetes)
Requirement already up-to-date: websocket-client in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: ipaddress in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/ipaddress-1.0.18-py2.7.egg (from kubernetes)
Requirement already up-to-date: setuptools in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: oauth2client in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/oauth2client-4.0.0-py2.7.egg (from kubernetes)
Requirement already up-to-date: six in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: appdirs>=1.4.0 in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages (from setuptools->kubernetes)
Requirement already up-to-date: packaging>=16.8 in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages (from setuptools->kubernetes)
Requirement already up-to-date: httplib2>=0.9.1 in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/httplib2-0.10.3-py2.7.egg (from oauth2client->kubernetes)
Requirement already up-to-date: pyasn1>=0.1.7 in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pyasn1-0.2.2-py2.7.egg (from oauth2client->kubernetes)
Requirement already up-to-date: pyasn1-modules>=0.0.5 in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pyasn1_modules-0.0.8-py2.7.egg (from oauth2client->kubernetes)
Requirement already up-to-date: rsa>=3.1.4 in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/rsa-3.4.2-py2.7.egg (from oauth2client->kubernetes)
Requirement already up-to-date: pyparsing in /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages (from packaging>=16.8->setuptools->kubernetes)
Installing collected packages: kubernetes
  Found existing installation: kubernetes 1.0.0b1
    Uninstalling kubernetes-1.0.0b1:
      Successfully uninstalled kubernetes-1.0.0b1
Successfully installed kubernetes-1.0.0b3
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/kubernetes-1.0.0b1-py2.7.egg'
```

**Comment by mbohlool** [comment]
I can't reproduce it. This is what I did:

```bash
/tmp$ source /tmp/bin/activate
(tmp) $VIRTUAL_ENV$ pip list --format=columns
Package    Version
---------- -------
appdirs    1.4.2  
packaging  16.8   
pip        9.0.1  
pyparsing  2.1.10 
setuptools 34.3.0 
six        1.10.0 
wheel      0.29.0 
(tmp) $VIRTUAL_ENV$ pip install ~/Downloads/kubernetes-1.0.0b1-py2.py3-none-any.whl 
Processing /Users/mehdy/Downloads/kubernetes-1.0.0b1-py2.py3-none-any.whl
Collecting ipaddress (from kubernetes==1.0.0b1)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting oauth2client (from kubernetes==1.0.0b1)
  Using cached oauth2client-4.0.0-py2.py3-none-any.whl
Collecting urllib3>=1.19 (from kubernetes==1.0.0b1)
  Using cached urllib3-1.20-py2.py3-none-any.whl
Collecting pyyaml (from kubernetes==1.0.0b1)
Requirement already satisfied: six>=1.10 in ./lib/python2.7/site-packages (from kubernetes==1.0.0b1)
Collecting python-dateutil (from kubernetes==1.0.0b1)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting certifi (from kubernetes==1.0.0b1)
  Using cached certifi-2017.1.23-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client->kubernetes==1.0.0b1)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client->kubernetes==1.0.0b1)
  Using cached pyasn1-0.2.2-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client->kubernetes==1.0.0b1)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting httplib2>=0.9.1 (from oauth2client->kubernetes==1.0.0b1)
Installing collected packages: ipaddress, pyasn1, pyasn1-modules, rsa, httplib2, oauth2client, urllib3, pyyaml, python-dateutil, certifi, kubernetes
Successfully installed certifi-2017.1.23 httplib2-0.10.3 ipaddress-1.0.18 kubernetes-1.0.0b1 oauth2client-4.0.0 pyasn1-0.2.2 pyasn1-modules-0.0.8 python-dateutil-2.6.0 pyyaml-3.12 rsa-3.4.2 urllib3-1.20
(tmp) $VIRTUAL_ENV$ python -m pip install kubernetes --upgrade
Collecting kubernetes
  Using cached kubernetes-1.0.0b3-py2.py3-none-any.whl
Collecting websocket-client (from kubernetes)
Requirement already up-to-date: setuptools in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: oauth2client in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: six in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: pyyaml in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: ipaddress in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: python-dateutil in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: urllib3 in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: certifi in ./lib/python2.7/site-packages (from kubernetes)
Requirement already up-to-date: appdirs>=1.4.0 in ./lib/python2.7/site-packages (from setuptools->kubernetes)
Requirement already up-to-date: packaging>=16.8 in ./lib/python2.7/site-packages (from setuptools->kubernetes)
Requirement already up-to-date: pyasn1-modules>=0.0.5 in ./lib/python2.7/site-packages (from oauth2client->kubernetes)
Requirement already up-to-date: pyasn1>=0.1.7 in ./lib/python2.7/site-packages (from oauth2client->kubernetes)
Requirement already up-to-date: rsa>=3.1.4 in ./lib/python2.7/site-packages (from oauth2client->kubernetes)
Requirement already up-to-date: httplib2>=0.9.1 in ./lib/python2.7/site-packages (from oauth2client->kubernetes)
Requirement already up-to-date: pyparsing in ./lib/python2.7/site-packages (from packaging>=16.8->setuptools->kubernetes)
Installing collected packages: websocket-client, kubernetes
  Found existing installation: kubernetes 1.0.0b1
    Uninstalling kubernetes-1.0.0b1:
      Successfully uninstalled kubernetes-1.0.0b1
Successfully installed kubernetes-1.0.0b3 websocket-client-0.40.0
(tmp) $VIRTUAL_ENV$ 
```

**Comment by mrmcmuffinz** [comment]
I need to put some more comments to explain the process I went through inorder to get that result. I'm also missing information such as the python version and os, so I will edit my original post to include that information.

**Comment by mrmcmuffinz** [comment]
I'm going to close this issue as I have not been able to reproduce and is probably not something worth my while looking into right now. I believe folks should just be deleting old client and doing fresh install while in beta. Will be closing this issue and if someone else reports the same they can reopen this one.
