### ISSUE TITLE
Websockets (`exec` and friends) broken in python 3.4

### ISSUE THREAD

**Issue by paultiplady** [kubernetes-incubator/client-python#156]
I'm getting the following client error when trying to exec in a running container:

```
Migrating database.
Traceback (most recent call last):
  File "/Users/paul/.virtualenvs/backend/lib/python3.4/site-packages/kubernetes/client/ws_client.py", line 241, in websocket_call
    client = WSClient(configuration, url, headers)
  File "/Users/paul/.virtualenvs/backend/lib/python3.4/site-packages/kubernetes/client/ws_client.py", line 63, in __init__
    self.sock.connect(url, header=header)
  File "/Users/paul/.virtualenvs/backend/lib/python3.4/site-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/Users/paul/.virtualenvs/backend/lib/python3.4/site-packages/websocket/_http.py", line 77, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Users/paul/.virtualenvs/backend/lib/python3.4/site-packages/websocket/_http.py", line 179, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Users/paul/.virtualenvs/backend/lib/python3.4/site-packages/websocket/_http.py", line 160, in _wrap_sni_socket
    server_hostname=hostname,
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/ssl.py", line 815, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/Users/paul/.pyenv/versions/3.4.4/lib/python3.4/ssl.py", line 282, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname '<ip>' doesn't match either of 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'

```

This triggers PTSD from getting pykube up and running in Python 3.4, which ultimately required a fix in the Requests library: https://github.com/kelproject/pykube/issues/29

Haven't dug yet, but it looks like monkeypatching match_hostname should work, perhaps you could use the conditional import logic that requests uses to get a working implementation  (https://github.com/shazow/urllib3/pull/922/files#diff-56265c767cf4b6064d04e48538bf019fR6)

I think switching to Python3.5 would also be a valid workaround, but that's not an option for users tied to OS-bundled versions.

**Comment by mbohlool** [comment]
did you use pip to install kubernetes? can you provide version of packages kubernetes depends on? if ipaddress package exists and urllib3 version is  greater than what specified in requrements.txt, it should fix this error.

**Comment by paultiplady** [comment]
I did use pip, but I just noticed that my virtualenv had a super-old version that wasn't correctly updating deps, so it's possible this is a false alarm. Haven't had a chance to retest with python3.4 (just worked around this by using a new venv with python3.5). I'll circle back and confirm later -- looks good to close now though.

Thanks

**Comment by mbohlool** [comment]
ok, please reopen if the problem still exists.
