### ISSUE TITLE
import collections error on kubernetes import

### ISSUE THREAD

**Issue by pvdvreede** [kubernetes-incubator/client-python#220]
Hi there,

I am using python 3.5.1 with kubernetes 2.0.0 and the second I run my script it errors when it tries to import kubernetes with the following error:

```
Traceback (most recent call last):
  File "operator.py", line 1, in <module>
    from kubernetes import config, watch
  File "/usr/local/lib/python3.5/site-packages/kubernetes/__init__.py", line 15, in <module>
    import kubernetes.client
  File "/usr/local/lib/python3.5/site-packages/kubernetes/client/__init__.py", line 17, in <module>
    from .models.apps_v1beta1_deployment import AppsV1beta1Deployment
  File "/usr/local/lib/python3.5/site-packages/kubernetes/client/models/__init__.py", line 17, in <module>
    from .apps_v1beta1_deployment import AppsV1beta1Deployment
  File "/usr/local/lib/python3.5/site-packages/kubernetes/client/models/apps_v1beta1_deployment.py", line 14, in <module>
    from pprint import pformat
  File "/usr/local/lib/python3.5/pprint.py", line 37, in <module>
    import collections as _collections
  File "/usr/local/lib/python3.5/collections/__init__.py", line 10, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "/app/operator.py", line 1, in <module>
    from kubernetes import config, watch
  File "/usr/local/lib/python3.5/site-packages/kubernetes/config/__init__.py", line 16, in <module>
    from .incluster_config import load_incluster_config
  File "/usr/local/lib/python3.5/site-packages/kubernetes/config/incluster_config.py", line 17, in <module>
    from kubernetes.client import configuration
  File "/usr/local/lib/python3.5/site-packages/kubernetes/client/configuration.py", line 27, in <module>
    import urllib3
  File "/usr/local/lib/python3.5/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 3, in <module>
    import logging
  File "/usr/local/lib/python3.5/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/local/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.5/linecache.py", line 8, in <module>
    import functools
  File "/usr/local/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple'
```

I understand this is an issue where some package may have a `collections.py` when it is trying to use the standard library, but I have a single `operator.py` file in my folder and no collections stuff anywhere.

Am I doing something wrong here?

**Comment by pvdvreede** [comment]
This was due to my filename being operator.py, i assume there was another import from the std lib calling that name.
