### ISSUE TITLE
Unable to use with minikube

### ISSUE THREAD

**Issue by pokoli** [kubernetes-incubator/client-python#241]
I have setup a kubernetes cluster on my machine using [minikube](https://github.com/kubernetes/minikube) but when I try to run the python client to this cluster I get the following exception:

```
 » python -m examples.example1
Listing pods with their IPs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sergi/projectes/kubernetes-python/examples/example1.py", line 33, in <module>
    main()
  File "/home/sergi/projectes/kubernetes-python/examples/example1.py", line 26, in main
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "kubernetes/client/apis/core_v1_api.py", line 13650, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "kubernetes/client/apis/core_v1_api.py", line 13743, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "kubernetes/client/api_client.py", line 329, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "kubernetes/client/api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "kubernetes/client/api_client.py", line 361, in request
    headers=headers)
  File "kubernetes/client/rest.py", line 240, in GET
    query_params=query_params)
  File "kubernetes/client/rest.py", line 217, in request
    raise ApiException(status=0, reason=msg)
kubernetes.client.rest.ApiException: (0)
Reason: SSLError
hostname '192.168.99.100' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes'
```

I've added an entry to my /etc/hosts files to name the 192.168.99.100 ip to kuberentes, so I can access it using the kubernetes hostname:

```
 » ping kubernetes
PING kubernetes (192.168.99.100) 56(84) bytes of data.
64 bytes from kubernetes (192.168.99.100): icmp_seq=1 ttl=64 time=0.180 ms
64 bytes from kubernetes (192.168.99.100): icmp_seq=2 ttl=64 time=0.174 ms
64 bytes from kubernetes (192.168.99.100): icmp_seq=3 ttl=64 time=0.217 ms
```

Using kubeclt works as expected:

```
 » kubectl get pods                                                     
NAME                                             READY     STATUS    RESTARTS   AGE
cheddar-602147572-drx2p                          1/1       Running   1          10d
cheddar-602147572-vfrjw                          1/1       Running   1          10d
grafana-grafana-1742814040-bcxrp                 1/1       Running   1          9d
jenkins-jenkins-3677470981-9p10m                 1/1       Running   1          9d
prometheus-alerts-3948116012-67800               2/2       Running   2          10d
prometheus-kube-state-metrics-1313518899-gtw1c   1/1       Running   1          10d
prometheus-server-997239920-v8rw5                2/2       Running   2          10d
stilton-3709340536-l631x                         1/1       Running   1          10d
stilton-3709340536-zt86f                         1/1       Running   1          10d
wensleydale-3324317336-s2xb0                     1/1       Running   1          10d
wensleydale-3324317336-x7xb1                     1/1       Running   1          10d
```

**Comment by pokoli** [comment]
After reading some examples I just discovered that I can make it work with disabling assert_hotname in examples folder. The following patch solved it:
```
diff --git a/examples/example1.py b/examples/example1.py                       
index 214fd19..49ce0db 100644                                                  
--- a/examples/example1.py                                                     
+++ b/examples/example1.py                                                     
@@ -13,6 +13,7 @@                                                              
 # limitations under the License.                                              
                                                                               
 from kubernetes import client, config                                         
+from kubernetes.client import configuration                                   
                                                                               
                                                                               
 def main():                                                                   
@@ -20,6 +21,7 @@ def main():                                                  
     # utility. If no argument provided, the config will be loaded from        
     # default location.                                                       
     config.load_kube_config()                                                 
+    configuration.assert_hostname = False                                     
                                                                               
     v1 = client.CoreV1Api()     
```

I'm wondering if we should add this as default for examples in order to make then also work on testing environments. If so, I will submit a PR

**Comment by mbohlool** [comment]
`minikube` works for me. I wonder if you have all requirements.txt packages fulfilled. Before your PR for merging setup.py's REQUIRED and requirements.txt, it was possible to not met the versioning requirement if you install the package with pip. check this: https://github.com/kubernetes-incubator/client-python#hostname-doesnt-match

**Comment by pokoli** [comment]
Yes, that was the issue. Solved installing the requeriments versions. 

Thanks you.
