### ISSUE TITLE
Trailing slash on kube/config causes failures.

### ISSUE THREAD

**Issue by karlbunch** [kubernetes-incubator/client-python#388]
Using the example1 code if your ~/.kube/config has an ending slash in the URL you get this failure:

```
Listing pods with their IPs:
Traceback (most recent call last):
  File "example1.py", line 33, in <module>
    main()
  File "example1.py", line 26, in main
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13589, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13686, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.5/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Sat, 11 Nov 2017 17:43:55 GMT', 'Content-Length': '524', 'Content-Type': 'application/json'})
HTTP response body: {
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/ping",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/swagger-2.0.0.json",
    "/swagger-2.0.0.pb-v1",
    "/swagger-2.0.0.pb-v1.gz",
    "/swagger.json",
    "/swaggerapi",
    "/version"
  ]
}
```

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://master.example.net:6443/
  name: master.example.net
```

If you remove the trailing slash in the config file it works fine.  kubectl has no issue with the trailing slash.

**Comment by karlbunch** [comment]
Looks like just adding rstrip('/') here fixes it:

https://github.com/kubernetes-client/python-base/blob/a41c44715241552de73361673152f3f0d0bb9bc4/config/kube_config.py#L227

**Comment by tomplus** [comment]
This issue is related to #375
